version: "2"
services:
  vh_mysql:
    build: ./mysql
    container_name: "vh_mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /wns/host/mysql/config/mysql.cnf:/etc/mysql/mysql.cnf
      - /wns/host/mysql/config/conf.d/:/etc/mysql/conf.d/
      - /wns/host/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  vh_redis:
    build: ./redis
    container_name: "vh_redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /wns/host/redis/data:/data
  vh_php:
    build: ./php-fpm
    container_name: "vh_php"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /wns/webui:/var/www/html
      - /wns/host/php-fpm/config:/usr/local/etc
      - /wns/host/php-fpm/log:/usr/local/var/log
    links:
      - "vh_mysql"
      - "vh_redis"
  vh_web:
    build: ./web
    container_name: "vh_web"
    restart: always
    ports:
      - "80:80"
    links:
      - "vh_php"
    volumes:
      - /wns/webui:/usr/share/nginx/html
      - /wns/host/web/config/nginx.conf:/etc/nginx/nginx.conf
      - /wns/host/web/config/conf.d:/etc/nginx/conf.d
      - /wns/host/web/log:/var/log/nginx